# Generated by Django 6.0.7 on 2026-08-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_coupon_order_coupon_code_order_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='risk_reasons',
            field=models.TextField(blank=True),
        ),
    ]
